created and tested method fot search users
JujaLabs/gamification-slack-bot pull request #17
Opened 2017-03-10 20:08 UTC by atem085

2017-03-11 20:17 UTC, vitvyaz commented
I think, we should use USR-F2 from "[JUJA][ТЗ] Users Microservice Public". In this feature we use parameters of HTTPrequest. For example: /users/search?slack=@ivan.petrov. Request body should be empty.

2017-03-13 08:39 UTC, adaleorion requested changes
@atem085 cделал ревью, посмотри пожалуйста

плюс подключи pull request к таске
добавь в комментарий к  pull request строку вида `` connect to #17 `` 

пример как делал я
https://github.com/JuniorsJava/gamification-slack-bot/pull/9

2017-03-13 08:39 UTC, adaleorion commented on build.gradle
> +    testCompile 'com.lordofthejars:nosqlunit-mongodb:0.8.1'
Где используется эта либа ?

2017-03-13 08:39 UTC, adaleorion commented on src/main/java/juja/microservices/gamification/slackbot/dao/UserRepository.java
> +    User searchUser(String userData);
мне кажется что тут слишком общий метод получился, не совсем понятно как использовать его методом, и какие параметры передавать
если поиск идет по slack nickname, то на мой взгляд, проще для понимания такая сигнатура -   findUserBySlack (String slackNickname)

2017-03-13 08:39 UTC, adaleorion commented on src/main/java/juja/microservices/gamification/slackbot/model/User.java
> +    public boolean equals(Object o) {
может для equals and hascode использовать lombok ?
https://projectlombok.org/features/EqualsAndHashCode.html

2017-03-13 08:39 UTC, danilkuznetsov commented on src/main/java/juja/microservices/gamification/slackbot/service/DefaultUserService.java
> +    public User searchUser(String dataUser) {
в этом случае по аналогии с dao слоем

2017-03-13 08:39 UTC, danilkuznetsov commented on src/main/java/juja/microservices/gamification/slackbot/dao/RestUserRepository.java
> +       HttpEntity request = new HttpEntity<>(userData, setupBaseHttpHeaders());
в этом методе есть небольшая проблема, наш user сервис ожидает запрос к себе с помощью GET с передачей параметров через url, 
про передачу с помощью  параметров говорит комментарий  
```
Request Body
No request body
```

переделай пожалуйста под это требование

2017-03-13 08:39 UTC, danilkuznetsov commented on src/test/java/juja/microservices/gamification/slackbot/dao/RestUserRepositoryTest.java
> +        User result = userRepository.searchUser("mail@gmail.com");
передается только значение параметра, но него его имя, как узнать по чему искать ? 
как я отмечал выше лучше сделать отдельный метод который будет искать по одному параметру при этом получая значение в качестве входных данных

2017-03-14 08:47 UTC, NikolayNN commented on src/main/java/juja/microservices/gamification/slackbot/model/Interview.java
> +public class Interview {
я считаю, что  класс нужно переименовать в InterviewAchievement, т.к. все классы в этом пакете с такой приставкой.

2017-03-15 20:00 UTC, adaleorion reviewed
молодец, нормально получилось, поправь плиз по комментам т.к. из-за этого merge conflict

2017-03-15 20:00 UTC, danilkuznetsov commented on src/test/java/juja/microservices/gamification/slackbot/dao/RestGamificationRepositoryTest.java
> +
удали плиз это строчку из-за нее merge conflict

2017-03-15 20:00 UTC, danilkuznetsov commented on src/main/java/juja/microservices/gamification/slackbot/service/DefaultGamificationService.java
> +
удали плиз это строчку из-за нее merge conflict

2017-03-15 20:00 UTC, danilkuznetsov commented on src/main/java/juja/microservices/gamification/slackbot/dao/RestGamificationRepository.java
> -
добавь плиз сюда пустую строчку из-за нее merge conflict

2017-03-15 20:01 UTC, danilkuznetsov commented
Еще на будущее при обращайся к доке со шпаргалкой по процессу, чтобы не забывать именовать правильно commit и т.п.

2017-03-16 15:04 UTC, danilkuznetsov commented on src/main/java/juja/microservices/gamification/slackbot/dao/RestGamificationRepository.java
> -
забыл еще поправить здесь :)

2017-03-16 15:23 UTC, adaleorion reviewed
попробуй еще раз

2017-03-16 15:23 UTC, danilkuznetsov commented on src/main/java/juja/microservices/gamification/slackbot/dao/RestGamificationRepository.java
> +
не в той строке сделал

2017-03-17 16:37 UTC, adaleorion approved these changes

2017-03-17 16:37 UTC, merged