#5 Create handler for "condenjoy" command
JujaLabs/gamification-slack-bot pull request #18
Opened 2017-03-14 06:56 UTC by NikolayNN

2017-03-14 07:20 UTC, NikolayNN commented on src/main/java/juja/microservices/gamification/slackbot/controller/SlackCommandController.java
> +    }
я не знаю стоит ли вводить еще какие-нибудь проверки кроме токена.
полный список параметров от слака
@param token
     * @param teamId
     * @param teamDomain
     * @param channelId
     * @param channelName
     * @param userId
     * @param userName
     * @param command
     * @param text
     * @param responseUrl

2017-03-14 07:20 UTC, NikolayNN commented on src/main/java/juja/microservices/gamification/slackbot/controller/SlackCommandController.java
> +    }
И наверное на этом уровне нужно еще отлавливать WrongCommandFormatException, чтобы текст из него вставлять в RichMessage. чтобы пользователь в слаке видел что пошло не так

2017-03-14 07:20 UTC, NikolayNN commented on src/main/java/juja/microservices/gamification/slackbot/exceptions/WrongCommandFormatException.java
> +}
Возможно более красиво будет IllegalCommandFormatException

2017-03-14 07:26 UTC, NikolayNN commented on src/test/java/juja/microservices/gamification/slackbot/controller/SlackCommandControllerTest.java
> +    }
добавить тесты если неправильный текст комманды

2017-03-14 13:41 UTC, adaleorion commented on src/main/java/juja/microservices/gamification/slackbot/controller/SlackCommandController.java
> +    public SlackCommandController(GamificationService gamificationService) {
Добавь плиз аннотацию inject, spring хоть и позволяет этого не делать, но так будет понятнее что происходит

2017-03-14 13:41 UTC, adaleorion commented on src/main/java/juja/microservices/gamification/slackbot/controller/SlackCommandController.java
> +public class SlackCommandController {
Т.к. наш бот будет в дальнейшем будет принимать и обрабатывать много разных команд, думаю лучше назвать GamificationSlackCommandController, что бы потом не путаться

2017-03-14 13:41 UTC, adaleorion commented on src/main/java/juja/microservices/gamification/slackbot/controller/SlackCommandController.java
> +    }
думаю что токена пока будет достаточно, 
при не правильной команде необходимо выводить подсказку как правильно ей пользоваться, по аналогии с linux

2017-03-14 13:41 UTC, adaleorion commented on src/test/java/juja/microservices/gamification/slackbot/controller/SlackCommandControllerTest.java
> +    }
отметь это в коде с помощью todo

2017-03-14 13:41 UTC, adaleorion commented on src/main/java/juja/microservices/gamification/slackbot/utils/CodenjoyHandler.java
> +    private List<String> recieveUserNamesBySlackNames(List<String> slackNames) {
этот метод лучше перенести в UserService,
сделаю задачу в backlog на него

2017-03-14 13:41 UTC, adaleorion commented on src/main/java/juja/microservices/gamification/slackbot/utils/CodenjoyHandler.java
> +        return new CodenjoyAchievment(from, userNames.get(0), userNames.get(1), userNames.get(2));
по API Gamification мы должны передать ей  uuid пользователей которые вернет нам user-microservice
то есть тут нужно взять из User его uuid через getter

2017-03-20 21:13 UTC, NikolayNN commented
pull request update.
вот какое у меня решение получилось.
__________________________
как вообще все это работает
SlackCommandController отлавливает post запросы из slack чата.
Потом по параметрам из этого запроса создается Command, который передается в AchievmentFactory где Command сначала передается в SlackNameHandlerService в нем Command обрабатывается следующим образом находятся все slack names и заменяются на uuid выделенные маркерами @# и #@ т.е. к примеру "text @#uuid#@ text".
и потом обработанная Command передается в фабричный метод класса AchievmentFactory. Где по имени команды определяется нужный AchievmentParcer который который парсит Command и отдает уже Achievement либо WrongCommandFormatException если что-то пошло не так. 
этот Achievment отправляется в микросервис по геймификации и отдается в чат ответ успешно было это или нет. 
ну и все в принципе.
_________________
для того чтобы это все стало возможно пришлось внести некоторые изменения в архитектуру проекта а именно:
добавлен интерфейс Achievement, с абстрактным методом ObjectNode toJson(); Этот метод предполагает что любой объект который реализует свой интерфейс обязан уметь конвертировать себя в JSON.  Все Achievments нужно наследовать от этого интерфейса.
стало возможным унифицировать методы интерфейса GamificationService и GamificationRepository
т.е. сейчас они могут состоять просто из одного метода. Я пока не убирал старые методы.
________________
чтобы добавить новый Achievement теперь достаточно:
1. создать класс к примеру NewAchievement implements Achievement
2. создать класс парсер для этой комманды  implements AchievmentParcer
3. добавить метод в SlackCommandController который будет мапиться на post запрос из slack чата
_________________
все это от части работает, и часть протестированно, но нужно еще рефакторить и добавлять тесты.

2017-03-21 16:32 UTC, atem085 commented on src/main/java/juja/microservices/gamification/slackbot/service/SlackNameHandlerService.java
> +        checkSlackName(command.getFromUser());
Double same check
if (command.getFromUser() == null)

2017-03-23 07:29 UTC, atem085 commented on src/main/java/juja/microservices/gamification/slackbot/controller/GamificationSlackCommandController.java
> +    private RichMessage getRichMessage(String token, Command command, String urlForSend) {
urlForSend doesn't use this method

2017-03-23 10:41 UTC, NikolayNN commented on src/main/java/juja/microservices/gamification/slackbot/controller/GamificationSlackCommandController.java
> +    private RichMessage getRichMessage(String token, Command command, String urlForSend) {
yes, I did update yesterday and forgot update here.  I will fix it today.

2017-03-27 14:49 UTC, starikivan commented on application.properties
> +parcedUuid.pattern=@#([a-zA-z0-9\\.\\_\\-]){1,21}#@
Предлагаю перенести application.properties в src/main/resources

2017-03-27 14:53 UTC, starikivan commented on src/main/java/juja/microservices/gamification/slackbot/dao/GamificationRepository.java
>  package juja.microservices.gamification.slackbot.dao;
можно перенести в juja.microservices.gamification.slackbot.dao.impl

2017-03-27 19:19 UTC, adaleorion requested changes
Как внесешь изменения после нашего обсуждения, отпишись пожалуйста 

я принял pr от Артема, теперь у нас есть метод который сразу возвращает uuid, обновись пожалуйста

2017-03-29 18:25 UTC, adaleorion approved these changes
well done.

2017-03-29 18:25 UTC, danilkuznetsov commented on application.properties
> +parcedUuid.pattern=@#([a-zA-z0-9\\.\\_\\-]){1,21}#@
спасибо, перенес в отдельную задачу

2017-03-29 18:25 UTC, danilkuznetsov commented on src/main/java/juja/microservices/gamification/slackbot/dao/GamificationRepository.java
>  package juja.microservices.gamification.slackbot.dao;
спасибо, перенес в отдельную таску

2017-03-29 18:25 UTC, danilkuznetsov commented on src/main/java/juja/microservices/gamification/slackbot/exceptions/WrongCommandFormatException.java
> +}
мне кажется что нормально, пока оставим так, в будущем посмотрим

2017-03-29 18:25 UTC, merged