#23:added method returning user's uuid
JujaLabs/gamification-slack-bot pull request #26
Opened 2017-03-20 16:13 UTC by atem085

connect to #23

2017-03-21 19:14 UTC, NikolayNN commented on src/main/java/juja/microservices/gamification/slackbot/dao/RestUserRepository.java
> +
to do method inject from this code:
try {
ResponseEntity response = this.restTemplate.getForEntity(urlTemplate, User.class, urlVariables);
uuidUser = response.getBody().getUuid();
} catch (HttpClientErrorException ex) {
throw new GamificationExchangeException("User Exchange Error: ", ex);
}

and use the method at the findUserBySlack() and findUuidUserBySlack()

2017-03-22 13:33 UTC, adaleorion requested changes

2017-03-22 13:33 UTC, danilkuznetsov commented on src/main/java/juja/microservices/gamification/slackbot/dao/RestUserRepository.java
> +
or use method findUserBySlack inside findUuidUserBySlack

2017-03-22 13:33 UTC, danilkuznetsov commented on src/test/java/juja/microservices/gamification/slackbot/dao/RestUserRepositoryTest.java
> +    public void shouldReturnUuidUserWhenSendUserDataToRemoteUserService() {
add test case which tests throw exception

2017-03-22 19:20 UTC, NikolayNN commented on src/main/java/juja/microservices/gamification/slackbot/dao/RestUserRepository.java
> +
yeah this is better way

2017-03-23 13:11 UTC, NikolayNN commented on src/test/java/juja/microservices/gamification/slackbot/dao/RestUserRepositoryTest.java
> +        mockServer.expect(requestTo("http://user.juja.com.ua/users/search/slackNickname=@user"))
read URLs from properties, like in the RestUserRepository.
because if we will change the URL into property file, the test will crash.

2017-03-23 17:26 UTC, NikolayNN commented
it looks good))

2017-03-27 19:17 UTC, adaleorion approved these changes

2017-03-27 19:17 UTC, merged