#6 Daily handler
JujaLabs/gamification-slack-bot pull request #32
Opened 2017-04-05 05:17 UTC by VadimDyachenko

connect to #6 

Created handler for "daily" command

2017-04-05 18:39 UTC, NikolayNN reviewed
it looks good

2017-04-06 13:53 UTC, adaleorion requested changes
спасибо, хорошая работа, подправь пожалуйста по комменту

2017-04-06 13:53 UTC, danilkuznetsov commented on src/test/java/juja/microservices/gamification/slackbot/controller/GamificationSlackCommandControllerTest.java
> +    public void onReceiveSlashCommandCodenjoy_When_IncorrectToken_Should_ReturnSorryRichMessage() throws Exception {
пожалуйста убери _ в названии теста, пускай они у нас буду в одном формате

2017-04-06 18:46 UTC, VadimDyachenko commented on src/test/java/juja/microservices/gamification/slackbot/controller/GamificationSlackCommandControllerTest.java
> +    public void onReceiveSlashCommandCodenjoy_When_IncorrectToken_Should_ReturnSorryRichMessage() throws Exception {
Исправил

2017-04-06 19:16 UTC, danilkuznetsov commented on src/test/java/juja/microservices/gamification/slackbot/controller/GamificationSlackCommandControllerTest.java
> +    public void onReceiveSlashCommandCodenjoy_When_IncorrectToken_Should_ReturnSorryRichMessage() throws Exception {
спасибо, пускай все будет в одном стиле

2017-04-06 19:16 UTC, adaleorion approved these changes

2017-04-06 19:16 UTC, merged