#74 implements new architecture throught new class SlackParsedCommand.
JujaLabs/gamification-slack-bot pull request #75
Opened 2017-07-03 09:36 UTC by NikolayNN

the pull request include tasks #62 #61 #53 #52.
implements features:
- slackbot do only one request for user microservice
- achievements created from SlackParsedCommand
- correct answers to slack with slack names
- new SlackNameHandler

2017-07-03 20:21 UTC, adaleorion requested changes
Would you change target branch in develop branch please.

2017-07-05 20:25 UTC, OlgaKulikova commented
@NikolayNN now you can change target branch to develop.  Then I will check and merge this pull request.

2017-07-07 20:28 UTC, OlgaKulikova commented on src/main/java/juja/microservices/gamification/slackbot/model/SlackParsedCommand.java
> +    private String from;
предлагаю в комманде поле from назвать fromSlackname, а в ачивках поле from - fromUuid. Потому что надо некоторое время, чтобы понять, что это разные фромы. Разное содержание.

2017-07-07 20:28 UTC, OlgaKulikova commented on src/main/java/juja/microservices/gamification/slackbot/model/achievements/CodenjoyAchievement.java
> +    private Map<String, UserDTO> getUsersForTokens(SlackParsedCommand parsedCommand, String[] tokens) {
этот метод лишняя прослойка. В конструкторе можно сразу вызвать `parsedCommand.getUsersWithTokens(tokens);`

2017-07-07 20:28 UTC, OlgaKulikova commented on src/main/java/juja/microservices/gamification/slackbot/model/achievements/InterviewAchievement.java
> +
лишняя пустая строка

2017-07-07 20:28 UTC, OlgaKulikova commented on src/main/java/juja/microservices/gamification/slackbot/model/achievements/ResponseWithSlackName.java
> + */
поменяй на формат `@author`

2017-07-07 20:28 UTC, OlgaKulikova commented on src/main/java/juja/microservices/gamification/slackbot/model/achievements/ThanksAchievement.java
> +        this.to = toUser.getUuid();
а поле to заменить на toUuid. Когда у нас было по одному варианту - можно было понять, что это uuid, но сейчас можно запутаться.

2017-07-09 08:31 UTC, NikolayNN commented on src/main/java/juja/microservices/gamification/slackbot/model/SlackParsedCommand.java
> +    private String from;
done

2017-07-09 08:31 UTC, NikolayNN commented on src/main/java/juja/microservices/gamification/slackbot/model/achievements/CodenjoyAchievement.java
> +    private Map<String, UserDTO> getUsersForTokens(SlackParsedCommand parsedCommand, String[] tokens) {
done

2017-07-09 08:38 UTC, NikolayNN commented on src/main/java/juja/microservices/gamification/slackbot/model/achievements/InterviewAchievement.java
> +
done

2017-07-09 08:38 UTC, NikolayNN commented on src/main/java/juja/microservices/gamification/slackbot/model/achievements/ResponseWithSlackName.java
> + */
done

2017-07-09 08:38 UTC, NikolayNN commented on src/main/java/juja/microservices/gamification/slackbot/model/achievements/ThanksAchievement.java
> +        this.to = toUser.getUuid();
done

2017-07-09 18:32 UTC, OlgaKulikova approved these changes

2017-07-09 18:34 UTC, merged